### PR TITLE
iholmes submission

### PR DESCRIPTION
**Pull request by iholmes**
Hi!

### CODE REVIEW

**Comment by pschloss** [comment]
Hey there,

It doesn't look like your formatting came through. As a hint, you'll need to insert spaces between the \* or + and your text. You might also have RStudio knit the html document to make sure it looks like you want before you post a merge request. Could you try again?

**Comment by iholmes** [comment]
Thanks - doing it now!

**Comment by iholmes** [comment]
hopefully this works

**Comment by pschloss** [comment]
Much better - want to try and throw in some links to things?

**Comment by iholmes** [comment]
Did my link to CRAN work?

**Comment by pschloss** [comment]
ah, i didn't see that the R was hyperlinked. looks good.

**Pull request closed without merging**
