### PR TITLE
M.Schmidt submission of syllabus.rmd

### PR DESCRIPTION
**Pull request by marschmi**
schmidt manipulated syllabus

### CODE REVIEW

**Comment by pschloss** [comment]
Marian - good work - one small thing - at the bottom you have a figure embedded where the address is to your computer. can you make it relative to the folder you're in?

**Comment by marschmi** [comment]
Pat, I have added the image to the assignment01 directory and have changed
the path.  Unfortunately, I still can't get the image to show.  Not sure
what I'm doing wrong.

**Comment by pschloss** [comment]
Marian, in the syllabus.md file this line...


Should be 


Also, it looks like you have mixed together the repositories for problems 2 and 3. If you look at the assignment it shows that they should be separate. This repository is for problem 2 and the microbialinformatics/microbialinformatics.github.io repository is for problem 3. Can you fix these?

**Comment by marschmi** [comment]
Hi Pat,

My computer was showing that error again when I try to push the new
repository on my github, so I merged the repositories.  I looked at the
same webpage that we did at the end of class on Friday.  Below is how far
I've made it where I change the url but I can't figure out how to
submit/commit the changes to the url.  This is something very simple but
unfortunately, can't figure it out.  Could you help me with it at the end
of class tomorrow?

Thanks for the help,
~Marian

[image: Inline image 1]

**Comment by pschloss** [comment]
Yeah, we can talk tomorrow after class.

**Comment by pschloss** [comment]
Good job!

**Pull request closed without merging**
